### ISSUE TITLE
System assumes spread operator enabled

### ISSUE THREAD

**Issue by kkinder** [ALiangLiang/vue-webpack-chrome-extension-template#4]
After following the install instructions, when you run `run dev`, you'll get this.

    npm run dev
    
    > example-chrome-text@1.0.0 dev /home/ken/playground/example-chrome-text
    > webpack --config ./build/webpack.dev.js --hide-modules
    
    /home/ken/playground/example-chrome-text/build/webpack.base.js:47
    ...cssLoaders(),
    ^^^
    
    SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ken/playground/example-chrome-text/build/webpack.dev.js:4:21)
    
It appears the default babel config doesn't enable the spread operator.

**Comment by ALiangLiang** [comment]
um...... I think you need [Nodejs version equal or upper than 8](https://node.green/#ES2018-features-object-rest-spread-properties). Because this part is belong to webpack script instead of babel.

But I will update that for compatible with [nodejs6](https://github.com/nodejs/Release#release-schedule).

**Comment by kkinder** [comment]
Ah, upgrading Node did the trick. Thanks!
