### ISSUE TITLE
getting error in ...cssLoaders(),

### ISSUE THREAD

**Issue by anand-tiwari** [ALiangLiang/vue-webpack-chrome-extension-template#7]
/Users/anandtiwari/Documents/my-project/build/webpack.base.js:47
          ...cssLoaders(),
          ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by anand-tiwari** [comment]
after replacing this 
loaders: {
          ...cssLoaders(),
          js: { loader: 'babel-loader' }
        },

with 
loaders: cssLoaders({sourceMap: false}),
     its working

**Comment by ALiangLiang** [comment]
This problem caused by lower nodejs version, "spread operator" need nodejs version upper or equal than 8. I think I must add a notes to hint everyone use newer version. Or even make it compatible with Nodejs6 until it no longer in "maintainence" stage. Thank for your report and fix method.

![image](https://user-images.githubusercontent.com/6974496/43523906-5f19cd64-95d0-11e8-8bee-b0ca91ca885b.png)

**Comment by anand-tiwari** [comment]
thanks @ALiangLiang
